# Generated by Django 4.0.3 on 2023-11-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Narrativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30000, verbose_name='descripcion')),
            ],
        ),
    ]
